List:
  - "<のり>ただの社会人のるのるさんに似てめんどくさそう"
  - "<のり>黒人と同性愛者が嫌いです"
  - "<のり>KUNLabガイジしかいないから"
  - "<のり>あのキモイおじさん、ウケてるようだったから今まで泳がせてたけどそろそろつぶすか"
  - "<のり>ながつきおもろい?"
  - "<のり>こいつも陽キャかよ、根暗数学陰キャだと思ってたのにむかつく>>hide__kunさん"
  - "<のり>うみにゃとかの配信見てるのマジで暇か隙間産業だけ"
  - "<のり>たこわさ羨ましい。俺もマイクラ入りたいよ。お願い。>>いもむしさん"
  - "<のり>おにーたん。。。おまたから血がでてきたよ。。。ふぇぇ(n'。・~~・。'n)←言われてみたい"
  - "<のり>ゲイの気持ち分かってた気でいたけどやっぱわからんわ"
  - "<のり>机の上におきっぱにしてたシコティッシュ親にばれて捨てられてた"
  - "<のり>おばさん顔真っ赤で草>>????さん"
  - "<ちたも>女ということしか取り柄のないかわいそうな人>>????さん"