List:
  - "ただの社会人のるのるさんに似てめんどくさそう"
  - "黒人と同性愛者が嫌いです"
  - "KUNLabガイジしかいないから"
  - "あのキモイおじさん、ウケてるようだったから今まで泳がせてたけどそろそろつぶすか"
  - "ながつきおもろい?"
  - "こいつも陽キャかよ、根暗数学陰キャだと思ってたのにむかつく>>hide__kun"
  - "うみにゃとかの配信見てるのマジで暇か隙間産業だけ"
  - "たこわさ羨ましい。俺もマイクラ入りたいよ。お願い。>>imo64"
  - "おにーたん。。。おまたから血がでてきたよ。。。ふぇぇ(n'。・~~・。'n)←言われてみたい"
  - "参加勢のリークってやってる事しょーもなくないか"
  - "ゲイの気持ち分かってた気でいたけどやっぱわからんわ"
  - "机の上におきっぱにしてたシコティッシュ親にばれて捨てられてた"
  - "カイキングのツイコールかけてみたらめっちゃ微妙な空気になった。"